# Generated by Django 2.1.2 on 2018-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(default=None)),
                ('bidder_id', models.IntegerField(default=None)),
                ('min_days', models.CharField(default=None, max_length=500)),
                ('max_days', models.CharField(default=None, max_length=500)),
                ('price', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='bids_accept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_id', models.IntegerField(default=None)),
                ('post_id', models.IntegerField(default=None)),
                ('bidder_id', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_item_id', models.IntegerField(default=None)),
                ('description', models.CharField(default=None, max_length=255)),
                ('rating', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='gallery_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('user_item_id', models.IntegerField(default=None)),
                ('pictures', models.CharField(default=None, max_length=500)),
                ('pictures_thumb', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(default=None, max_length=255)),
                ('county', models.CharField(default=None, max_length=255)),
                ('ward', models.CharField(default=None, max_length=255)),
                ('province', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=255)),
                ('tags', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('location_id', models.IntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
                ('min_days', models.CharField(default=None, max_length=500)),
                ('max_days', models.CharField(default=None, max_length=500)),
                ('price', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(default=None, max_length=500)),
                ('user_id', models.IntegerField(default=None)),
                ('amount', models.IntegerField(default=None)),
                ('currency', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(default=None)),
                ('user_id', models.IntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
                ('price_for_lease', models.CharField(default=None, max_length=500)),
                ('location_id', models.IntegerField(default=None)),
                ('pictures', models.CharField(default=None, max_length=500)),
                ('pictures_thumb', models.CharField(default=None, max_length=500)),
                ('min_radius', models.IntegerField(default=None)),
                ('max_radius', models.IntegerField(default=None)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_items_payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('category_id', models.IntegerField(default=None)),
                ('amount', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_items_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('category_id', models.IntegerField(default=None)),
                ('status', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_payment_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('payment_status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(default='POSTER', max_length=255)),
                ('msisdn', models.CharField(default=None, max_length=255)),
                ('device_uid', models.CharField(default='JESUS', max_length=255)),
                ('stripe_id', models.CharField(default=None, max_length=255)),
                ('card_brand', models.CharField(default=None, max_length=255)),
                ('card_last_four', models.CharField(default=None, max_length=255)),
                ('trial_end_at', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
