# Generated by Django 2.1.2 on 2018-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_posts_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='adverts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('location_id', models.IntegerField(default=None)),
                ('category_id', models.IntegerField(default=1)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
                ('pictures', models.CharField(default=None, max_length=500)),
                ('price_id', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='adverts_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advert_id', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='pricing_adverts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=500)),
                ('days', models.CharField(default=None, max_length=500)),
                ('price', models.CharField(default=None, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
