# Generated by Django 2.1.2 on 2018-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_adverts_adverts_logs_pricing_adverts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_adverts',
            name='time',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
