# Generated by Django 2.1.2 on 2018-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_adverts_logs_nexttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_adverts',
            name='created_at',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
