# Generated by Django 2.1.2 on 2018-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0007_auto_20181117_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts_logs',
            name='nexttime',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
