# Generated by Django 2.1.2 on 2018-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0008_auto_20181117_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='updated_at',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='adverts_logs',
            name='created_at',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='adverts_logs',
            name='updated_at',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pricing_adverts',
            name='updated_at',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
