# Generated by Django 2.1.2 on 2018-11-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0009_auto_20181117_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='adverts_logs',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='adverts_logs',
            name='nexttime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='adverts_logs',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pricing_adverts',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pricing_adverts',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
